name: Build and Deploy Frontend

# Trigger the workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install

      # Build frontend
      - name: Build frontend
        run: npm run build

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t vinorelbine/rusty-next:latest --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t vinorelbine/rusty-next:${{ github.sha }} --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            sshpass -e docker compose down
            sshpass -e docker compose pull
            sshpass -e docker compose up -d
